### PR TITLE
Fix for Issue #201

### LINKED ISSUE #201: Can't successfully rerun the cookbook if set the wrong parameter the first time
If the first time I set the wrong parameter e.g node['rabbitmq']['address'] ,  the cookbook exited when restarting the rabbitmq.
Then second time I corrected the node['rabbitmq']['address'], and rerun the recipe, it will exited before the reconfigure the rabbitmq-env.conf file.  Because the recipe will try to start the rabbtimq before reconfigure at this line:   https://github.com/jjasghar/rabbitmq/blob/master/recipes/default.rb#L115-L117

### PR DESCRIPTION
**Pull request by jjasghar**
- Moved the service enable and start to the bottom of the default recipe so you can change variables around.
- This should resolve #201

### CODE REVIEW

File: recipes/default.rb [hunk 1]
```diff
@@ -129,9 +125,6 @@ class Chef::Resource # rubocop:disable all
     version node['rabbitmq']['version']
   end
 
-  service node['rabbitmq']['service_name'] do
-    action [:enable, :start]
```
Comment (wenchma) [inline recipes/default.rb]: other way,  only to enable the service and not start the service, is it more reasonable?   after configuring rabbit, it will be restart immediately now.
@jjasghar
